# Generated by Django 5.2.3 on 2025-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='disabled',
            field=models.BooleanField(default=False, help_text='This card is disabled and cannot be used'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
