# Generated by Django 5.2.3 on 2025-06-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_disabled_alter_card_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
    ]
