# Generated by Django 5.2.3 on 2025-06-22 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_card_name'),
        ('doors', '0006_alter_remoteclient_doors'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='This is the name of the registration terminal', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('door', models.ForeignKey(help_text='This refers to the door that this registration terminal is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='registration_terminals', to='doors.door')),
            ],
        ),
    ]
