# Generated by Django 5.2.3 on 2025-06-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_registrationterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationterminal',
            name='_singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
