# Generated by Django 3.2.15 on 2022-11-18 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oldest_serial', models.PositiveBigIntegerField(default=0)),
                ('newest_serial', models.PositiveBigIntegerField(default=0)),
                ('register_mode', models.BooleanField(default=False, help_text='Enabling this checkbox will allow any client to refresh this token once.This is a security risk, only use this for setting up new devices and check the functionality of your token immediately.It will also automatically be disabled upon any successful authorization.')),
                ('sync_mode', models.BooleanField(default=False, help_text='Enabling this checkbox will allow a client with an expired token to refresh this token once. This is a security risk, only use this after loss of synchronization with an end device (which may indicate api token theft).It will also automatically be disabled upon any successful authorization.')),
                ('user', models.ForeignKey(help_text='This is the user the api token authorizes as.', on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='apitoken',
            constraint=models.CheckConstraint(check=models.Q(('oldest_serial__lte', django.db.models.expressions.F('newest_serial'))), name='serial_range_constraint'),
        ),
    ]
