# Generated by Django 3.2.6 on 2021-08-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'permissions': [('open_door', 'Can open any door'), ('assume_correct_location', 'Can open doors from anywhere')]},
        ),
    ]
