# Generated by Django 5.2.3 on 2025-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='latest_ldap_directory_data',
            field=models.JSONField(blank=True, help_text='This field contains the newest known data about this user from the LDAP provider.', null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='latest_directory_data',
            field=models.JSONField(blank=True, help_text='This field contains the newest known data about this user from the OIDC provider. It might be outdated, though.', null=True),
        ),
    ]
