# Generated by Django 5.2.3 on 2025-06-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userconnection_latest_ldap_directory_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnection',
            name='latest_ldap_directory_data',
        ),
    ]
