# Generated by Django 3.2.3 on 2021-05-16 09:56

from django.db import migrations, models
import django.utils.timezone


# https://docs.djangoproject.com/en/3.2/topics/migrations/#data-migrations
def estimate_date(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('accounts', 'User')
    for person in User.objects.all():
        person.password_last_changed = person.date_joined
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20210516_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='password last changed'),
        ),
        migrations.RunPython(estimate_date),
    ]
