# Generated by Django 3.2.6 on 2021-08-29 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_password_last_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.TextField(blank=True, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directory_key', models.TextField(help_text='This is the unique ID provided by the directory to identify this user', unique=True)),
                ('latest_directory_data', models.JSONField(help_text='This field contains the newest known data about this user. It might be outdated, though.', null=True)),
                ('directory', models.ForeignKey(help_text='This refers to the directory used to log in the user', on_delete=django.db.models.deletion.CASCADE, to='accounts.userdirectory')),
                ('user', models.ForeignKey(help_text='This refers to a user who can be logged in using a directory', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
