# Generated by Django 3.2.6 on 2021-08-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210829_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirectoryUsers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.userdirectory',),
        ),
    ]
