# Generated by Django 3.2.7 on 2021-09-07 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mqtt_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('display_name', models.TextField()),
            ],
            options={
                'permissions': [('doors.open_door', 'Can open any door'), ('doors.assume_correct_location', 'Can open doors from anywhere')],
            },
        ),
    ]
