# Generated by Django 3.2.15 on 2022-11-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_alter_door_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={},
        ),
    ]
