# Generated by Django 4.2.4 on 2023-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_alter_door_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='button_color',
            field=models.CharField(help_text='HTML hex color code for button', max_length=7, default='#60b177', null=True),
        ),
        migrations.AddField(
            model_name='door',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of appearance for door buttons. Lower is higher up.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='door',
            name='text_color',
            field=models.CharField(help_text='HTML hex color code for text on button', max_length=7, default='#ffffff', null=True),
        ),
    ]
