# Generated by Django 5.1.1 on 2024-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0003_door_button_color_door_order_door_text_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'ordering': ('order',), 'permissions': [('open_door', 'Can open any door'), ('assume_correct_location', 'Can open doors from anywhere')]},
        ),
        migrations.AlterField(
            model_name='door',
            name='button_color',
            field=models.CharField(default='#60b177', help_text='HTML hex color code for button', max_length=7),
        ),
        migrations.AlterField(
            model_name='door',
            name='order',
            field=models.IntegerField(default=42, help_text='Order of appearance for door buttons. Lower is higher up.'),
        ),
    ]
