# Generated by Django 4.1.3 on 2023-08-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0003_alter_door_options'),
        ('doors', '0003_door_button_color_door_order_door_text_color'),
    ]

    operations = [
    ]
