# Generated by Django 5.2.3 on 2025-06-16 10:55

import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0004_alter_door_options_alter_door_button_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=256, unique=True)),
                ('token', encrypted_fields.fields.EncryptedCharField(max_length=256)),
                ('doors', models.ManyToManyField(related_name='remote_clients', to='doors.door')),
            ],
        ),
    ]
