# Generated by Django 5.1.1 on 2025-09-18 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0004_alter_door_options_alter_door_button_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MultiOpen',
            fields=[
                ('order', models.IntegerField(default=42, help_text='Order of appearance for door buttons. Lower is higher up.')),
                ('text_color', models.CharField(default='#ffffff', help_text='HTML hex color code for text on button', max_length=7, null=True)),
                ('button_color', models.CharField(default='#60b177', help_text='HTML hex color code for button', max_length=7)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('doors', models.ManyToManyField(to='doors.door')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
