# Generated by Django 5.2.3 on 2025-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0005_remoteclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteclient',
            name='doors',
            field=models.ManyToManyField(blank=True, related_name='remote_clients', to='doors.door'),
        ),
    ]
