# Generated by Django 5.2.6 on 2025-09-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0006_door_to_multiopen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'permissions': [('open_door', 'Can open any door'), ('assume_correct_location', 'Can open doors from anywhere')]},
        ),
        migrations.RemoveField(
            model_name='door',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='door',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='door',
            name='order',
        ),
        migrations.RemoveField(
            model_name='door',
            name='text_color',
        ),
    ]
