# Generated by Django 5.2.3 on 2025-09-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0006_alter_remoteclient_doors'),
        ('doors', '0007_alter_door_options_remove_door_button_color_and_more'),
    ]

    operations = [
    ]
